DROP TABLE IF EXISTS comments, requests, bookings, items, users;

CREATE TABLE IF NOT EXISTS users (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NULL,
	email varchar(255) NOT NULL UNIQUE,
	CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(255) NULL,
    requestor_id integer NOT NULL,
	CONSTRAINT request_pk PRIMARY KEY (id),
	CONSTRAINT request_fk FOREIGN KEY (requestor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	description varchar(255) NULL,
	is_available boolean,
	owner_id integer NOT NULL,
	request_id integer NULL,
	CONSTRAINT items_pk PRIMARY KEY (id),
	CONSTRAINT items_fk FOREIGN KEY (owner_id) REFERENCES users(id),
	CONSTRAINT items_fk2 FOREIGN KEY (request_id) REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id integer NOT NULL,
    booker_id integer NOT NULL,
    status varchar(255) NOT NULL,
	CONSTRAINT  booking_pk PRIMARY KEY (id),
	CONSTRAINT booking_fk FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT booking_fk2 FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS comments (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	text varchar(255) NULL,
    item_id integer NOT NULL,
    author_id integer NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
	CONSTRAINT comment_pk PRIMARY KEY (id),
	CONSTRAINT comment_fk FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
	CONSTRAINT comment_fk2 FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);




